"""add threat_whitelist table

Revision ID: b0c83ced5f41
Revises: d7d826087d4b
Create Date: 2026-04-19 23:38:54.032538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c83ced5f41'
down_revision = 'd7d826087d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_cidr', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_cidr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_whitelist')
    # ### end Alembic commands ###
