"""add threat_blocks table

Revision ID: c311838bd8a1
Revises: b0c83ced5f41
Create Date: 2026-04-20 00:01:40.015739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c311838bd8a1'
down_revision = 'b0c83ced5f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_blocks_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_blocks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threat_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_blocks_status'))
        batch_op.drop_index(batch_op.f('ix_threat_blocks_ip_address'))

    op.drop_table('threat_blocks')
    # ### end Alembic commands ###
