"""EDL (External Dynamic List) export service.

Exports blocklist and whitelist as plain-text files (one IP/CIDR per line)
for consumption by hardware firewalls (Palo Alto EDL, Fortinet External
Connector, etc.).

Files are re-exported on every list mutation. The export directory is
configured via BMW_EDL_EXPORT_DIR (default: <project>/edl_export/).

Output files:
    blocklist.txt  -- all currently active blocked IPs
    whitelist.txt  -- all whitelist entries
"""

import logging
import os
from datetime import datetime, timezone

from flask import current_app

from app.extensions import db
from app.models.threat_block import ThreatBlock
from app.models.threat_whitelist import ThreatWhitelist

log = logging.getLogger(__name__)


def _get_export_dir():
    """Return the configured EDL export directory, creating it if needed."""
    path = current_app.config.get("EDL_EXPORT_DIR", "edl_export")
    os.makedirs(path, exist_ok=True)
    return path


def _write_file(filepath, lines):
    """Atomically write lines to a file (write to tmp, then rename)."""
    tmp = filepath + ".tmp"
    with open(tmp, "w") as f:
        # Header comment (EDL-compatible -- lines starting with # are ignored by most firewalls)
        f.write(f"# Generated by BeakMeshWall at {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}\n")
        f.write(f"# Total entries: {len(lines)}\n")
        for line in sorted(lines):
            f.write(line + "\n")
    os.replace(tmp, filepath)


def export_blocklist():
    """Export all active blocked IPs to blocklist.txt."""
    export_dir = _get_export_dir()
    filepath = os.path.join(export_dir, "blocklist.txt")

    blocks = ThreatBlock.query.filter_by(status="active").all()
    ips = [b.ip_address for b in blocks]

    _write_file(filepath, ips)
    log.info("EDL blocklist exported: %d entries -> %s", len(ips), filepath)
    return filepath


def export_whitelist():
    """Export all whitelist entries to whitelist.txt."""
    export_dir = _get_export_dir()
    filepath = os.path.join(export_dir, "whitelist.txt")

    entries = ThreatWhitelist.query.all()
    cidrs = [e.ip_cidr for e in entries]

    _write_file(filepath, cidrs)
    log.info("EDL whitelist exported: %d entries -> %s", len(cidrs), filepath)
    return filepath


def export_all():
    """Export both blocklist and whitelist."""
    export_blocklist()
    export_whitelist()
